version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8050:8050"
    depends_on:
      - backend
    networks:
      - forecast_net

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    networks:
      - forecast_net

networks:
  forecast_net:
